### ISSUE TITLE
Ambiguous syntax with class static block

### ISSUE THREAD

**Issue by JLHwung** [tc39/proposal-grouped-and-auto-accessors#1]
```js
class C {
  static {
    get;
    set;
  }
}
```
can be i) a static block including two expression statements or ii) an auto accessors named as `"static"`

Ref: https://github.com/tc39/proposal-class-static-block

**Comment by rbuckton** [comment]
I'm aware, as I'm the champion of both proposals. I've mentioned it in the slides for the upcoming meeting. The conflict is the same as `constructor`, and is resolvable by allowing `["static"] { get; set; }` to mean the property, just as we do for `constructor`.

**Comment by JLHwung** [comment]
> The conflict is the same as constructor

I don't follow. A class can not have `constructor` a field name so `class { constructor }` is already invalid. But `static` is allowed.

> I've mentioned it in the slides for the upcoming meeting.

Ah I see, just checked out the slides. Will provide more feedback later.

**Comment by rbuckton** [comment]
What I mean with `constructor` is that you can define a prototype method named `constructor` using a computed property name that differs from the class constructor:

![image](https://user-images.githubusercontent.com/3902892/98725382-e6ff2e00-2349-11eb-9d0b-280b7d1a020c.png)
