### ISSUE TITLE
Conflict with proposal-decorators?

### ISSUE THREAD

**Issue by whzx5byb** [tc39/proposal-grouped-and-auto-accessors#12]
I notice that the decorator proposal (which is at stage 3) has already introduced the concept of [class auto accessors](https://github.com/tc39/proposal-decorators#class-auto-accessors). Does this conflict with that?

**Comment by rbuckton** [comment]
There should be no conflict. The class auto accessor functionality in the Decorators proposal was a collaboration between myself and the Decorators champion to ensure these proposals were closely aligned.
