### ISSUE TITLE
Conflict with static blocks?

### ISSUE THREAD

**Issue by pzuraq** [tc39/proposal-grouped-and-auto-accessors#4]
So my understanding was that one of the concerns for this proposal was that it would conflict with Static Blocks. I can see one potential conflict, for instance, the following would be a valid static block:

```js
class C {
  static { get; set; }
}
```

But then adding `=` at the end would turn it into an auto-accessor:

```js
class C {
  static { get; set; } = 123
}
```

Is this something we can address in the syntax itself? Is this a use case that is meaningful? Users could probably do:

```js
class C {
  ['static'] { get; set; }
}
```

If they wanted to define an auto-accessor named `static`.

**Comment by nicolo-ribaudo** [comment]
This is no longer an issue, since the proposal includes the explicit `accessor` prefix:
```js
class A {
  accessor static { get; set; }
}
```
