### ISSUE TITLE
Should we allow grouped get + #set collide with same name public setter?

### ISSUE THREAD

**Issue by JLHwung** [tc39/proposal-grouped-and-auto-accessors#8]
> We may choose to make it an early error to have both a grouped set and a grouped #set for the same name on the same class.

How should we handle the following grouped #set + ungrouped set cases?

```js
class C {
  accessor a { get; #set }
  set a(value) {}
}
```

If we decide to throw for grouped cases, then I think we should throw for the ungrouped example above, too. 

Of course if people are not using grouped/auto accessors at all, e.g.

```js
class C {
  get a() {}
  set #a(value) {}
  set a(value) {}
}
```

it should be completely fine per current spec.

**Comment by rbuckton** [comment]
For now I've decided to align with existing spec behavior if you have colliding declarations (i.e., they would merge at the end). However, I do restrict what's permitted *inside* of an AccessorGroup, so you cannot have `accessor x { get; set; #set; }`.
